package com.lanrhyme.micyou

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.text.intl.Locale

enum class AppLanguage(val label: String, val code: String) {
    System("System / 跟随系统", "system"),
    Chinese("简体中文", "zh"),
    English("English", "en")
}

data class AppStrings(
    val appName: String,
    val ipLabel: String,
    val portLabel: String,
    val targetIpLabel: String,
    val targetIpUsbLabel: String,
    val bluetoothAddressLabel: String,
    val connectionModeLabel: String,
    val modeWifi: String,
    val modeBluetooth: String,
    val modeUsb: String,
    val statusLabel: String,
    val statusIdle: String,
    val statusConnecting: String,
    val statusStreaming: String,
    val statusError: String,
    val muteLabel: String,
    val unmuteLabel: String,
    val micMuted: String,
    val micNormal: String,
    val settingsTitle: String,
    val close: String,
    val minimize: String,
    val start: String,
    val stop: String,
    val waitAdb: String,
    
    // Settings
    val generalSection: String,
    val appearanceSection: String,
    val audioSection: String,
    val aboutSection: String,
    val languageLabel: String,
    val themeLabel: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val autoStartLabel: String,
    val monitoringLabel: String,
    val sampleRateLabel: String,
    val channelCountLabel: String,
    val audioFormatLabel: String,
    val enableNsLabel: String,
    val nsTypeLabel: String,
    val enableAgcLabel: String,
    val agcTargetLabel: String,
    val enableVadLabel: String,
    val vadThresholdLabel: String,
    val enableDereverbLabel: String,
    val dereverbLevelLabel: String,
    val amplificationLabel: String,
    val openSourceLicense: String,
    val viewLibraries: String,
    val softwareIntro: String,
    val introText: String,
    
    val systemConfigTitle: String,
    
    // Missing keys
    val clickToStart: String,
    val autoStartDesc: String,
    val noGeneralSettings: String,
    val themeColorLabel: String,
    val amplificationMultiplierLabel: String,
    val licensesTitle: String,
    val basedOnAndroidMic: String,
    val developerLabel: String,
    val githubRepoLabel: String,
    val versionLabel: String
)

val EnStrings = AppStrings(
    appName = "MicYou",
    ipLabel = "IP: ",
    portLabel = "Port",
    targetIpLabel = "Target IP",
    targetIpUsbLabel = "Target IP (127.0.0.1)",
    bluetoothAddressLabel = "Bluetooth Device Address (MAC)",
    connectionModeLabel = "Connection Mode",
    modeWifi = "Wi-Fi",
    modeBluetooth = "Bluetooth",
    modeUsb = "USB",
    statusLabel = "Status: ",
    statusIdle = "Idle",
    statusConnecting = "Connecting...",
    statusStreaming = "Streaming",
    statusError = "Error",
    muteLabel = "Mute",
    unmuteLabel = "Unmute",
    micMuted = "Microphone Muted",
    micNormal = "Microphone Normal",
    settingsTitle = "Settings",
    close = "Close",
    minimize = "Minimize",
    start = "Start",
    stop = "Stop",
    waitAdb = "Waiting for ADB connection...",
    
    generalSection = "General",
    appearanceSection = "Appearance",
    audioSection = "Audio",
    aboutSection = "About",
    languageLabel = "Language",
    themeLabel = "Theme Mode",
    themeSystem = "System",
    themeLight = "Light",
    themeDark = "Dark",
    autoStartLabel = "Auto Start",
    monitoringLabel = "Monitoring (Desktop)",
    sampleRateLabel = "Sample Rate",
    channelCountLabel = "Channels",
    audioFormatLabel = "Audio Format",
    enableNsLabel = "Noise Suppression",
    nsTypeLabel = "Algorithm",
    enableAgcLabel = "AGC",
    agcTargetLabel = "Target Level",
    enableVadLabel = "VAD",
    vadThresholdLabel = "Threshold",
    enableDereverbLabel = "Dereverb",
    dereverbLevelLabel = "Level",
    amplificationLabel = "Amplification",
    openSourceLicense = "License",
    viewLibraries = "View Open Source Libraries",
    softwareIntro = "Introduction",
    introText = "MicYou is an open source microphone tool that turns your Android device into a high-quality microphone for your computer. Based on AndroidMic, it supports Wi-Fi (TCP), Bluetooth, and USB connections, providing low-latency audio transmission.",
    systemConfigTitle = "System Configuration",

    clickToStart = "Click to Start",
    autoStartDesc = "Start streaming automatically on app launch",
    noGeneralSettings = "No general settings available",
    themeColorLabel = "Theme Color",
    amplificationMultiplierLabel = "Multiplier",
    licensesTitle = "Open Source Libraries and Licenses",
    basedOnAndroidMic = "MicYou is based on AndroidMic.",
    developerLabel = "Developer",
    githubRepoLabel = "GitHub Repository",
    versionLabel = "Version"
)

val ZhStrings = AppStrings(
    appName = "MicYou",
    ipLabel = "IP: ",
    portLabel = "端口",
    targetIpLabel = "目标 IP",
    targetIpUsbLabel = "目标 IP (127.0.0.1)",
    bluetoothAddressLabel = "蓝牙设备地址 (MAC)",
    connectionModeLabel = "连接模式",
    modeWifi = "Wi-Fi",
    modeBluetooth = "蓝牙",
    modeUsb = "USB",
    statusLabel = "状态: ",
    statusIdle = "空闲",
    statusConnecting = "连接中...",
    statusStreaming = "正在传输",
    statusError = "错误",
    muteLabel = "静音",
    unmuteLabel = "取消静音",
    micMuted = "麦克风已静音",
    micNormal = "麦克风正常",
    settingsTitle = "设置",
    close = "关闭",
    minimize = "最小化",
    start = "开始",
    stop = "停止",
    waitAdb = "等待 ADB 连接...",
    
    generalSection = "通用",
    appearanceSection = "外观",
    audioSection = "音频",
    aboutSection = "关于",
    languageLabel = "语言",
    themeLabel = "主题模式",
    themeSystem = "跟随系统",
    themeLight = "亮色",
    themeDark = "暗色",
    autoStartLabel = "自动串流",
    monitoringLabel = "监听 (仅桌面)",
    sampleRateLabel = "采样率",
    channelCountLabel = "通道数",
    audioFormatLabel = "音频格式",
    enableNsLabel = "降噪 (Noise Suppression)",
    nsTypeLabel = "降噪算法",
    enableAgcLabel = "自动增益控制 (AGC)",
    agcTargetLabel = "目标电平",
    enableVadLabel = "语音活动检测 (VAD)",
    vadThresholdLabel = "阈值",
    enableDereverbLabel = "去混响 (Dereverb)",
    dereverbLevelLabel = "强度",
    amplificationLabel = "信号放大 (Amplification)",
    openSourceLicense = "开源许可",
    viewLibraries = "查看使用的开源库",
    softwareIntro = "软件介绍",
    introText = "MicYou 是一款开源的麦克风工具，可以将您的 Android 设备变成电脑的高质量麦克风，本软件基于 AndroidMic 进行开发，支持 Wi-Fi (TCP)、蓝牙 和 USB 连接，提供低延迟的音频传输体验。",
    systemConfigTitle = "系统配置中",

    clickToStart = "点击开始",
    autoStartDesc = "应用启动时自动开始串流",
    noGeneralSettings = "暂无通用设置",
    themeColorLabel = "主题颜色",
    amplificationMultiplierLabel = "倍数",
    licensesTitle = "Open Source Libraries and Licenses",
    basedOnAndroidMic = "MicYou 基于 AndroidMic 项目开发。",
    developerLabel = "开发者",
    githubRepoLabel = "Github 仓库",
    versionLabel = "版本"
)

val LocalAppStrings = staticCompositionLocalOf { ZhStrings }

fun getStrings(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.Chinese -> ZhStrings
        AppLanguage.English -> EnStrings
        AppLanguage.System -> {
            val locale = Locale.current.language
            if (locale.startsWith("zh")) ZhStrings else EnStrings
        }
    }
}
